### ISSUE TITLE
no_test undefined

### ISSUE THREAD

**Issue by familiarcat** [kristoferjoseph/sprout-robotlegs#2]
I've successfully installed the gem and built an application with rl-project but when I look to generate a proxy or service I receive the error: 
.rvm/gems/ruby-1.9.2-p136/gems/robotlegs-1.3.0.5.pre/lib/robotlegs/generators/service_generator.rb:11:in `manifest': undefined local variable or method`no_test' for #Robotlegs::ServiceGenerator:0x00000100c950a8 

I cant seem to find the "no_test" method, although it seems to be in the generator's manifest.

Thanks so much - I'm attempting to upgrade to the newest project sprouts and rl-generators but it all seems a bit too fresh to put into actual production.

**Comment by familiarcat** [comment]
I also found that downloading and compiling the gem from source using the directions you provided results in a Bundler::GemfileNotFound error when the gem is installed and rl-project is run. (the no_test error from the rl-service was from the remote gem)

Cheers

**Comment by kristoferjoseph** [comment]
The first issue was due to project sprouts removing the no_test method that my test were depending on. This has been fixed. 

The second issue has been fixed as well. The issue was due to having a Bundle.require call in my rl-project executable. This will not work unless you have specified a system wide default gemfile to satisfy Bundlers requirement of a gemfile.
